pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - body~=labels:.*semver-patch.*
      - status-success~=Build and Test \(2.12
      - status-success~=Build and Test \(2.13
    actions:
      merge:
        method: merge
